### ISSUE TITLE
Error in the docs: unknown shorthand flag

### ISSUE THREAD

**Issue by DiSiqueira** [VivaReal/x9#3]
When I try to follow the instruction on `How to build it and run in Docker` I had the following error:

```bash
% docker run -d -n redis redis
unknown shorthand flag: 'n' in -n
See 'docker run --help'.
```

My docker version:
```bash
% docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

You probably wanted to mean `docker run --name redis -d redis` I'll open a PR to fix, but i'll leave the issue here to make sure that this is the case.

**Comment by DiSiqueira** [comment]
Also I took the initiative to migrate the project to use Docker-compose, please take a look at this PR: https://github.com/VivaReal/x9/pull/5

**Comment by lorieri** [comment]
Hi, thanks :)
I meant --name
Thanks for the other contributions too.
